### ISSUE TITLE
Unable to compile datetime, socket and time extensions with shared python 2.7.9

### ISSUE THREAD

**Issue by adrianbroher** [davidsansome/python-cmake-buildsystem#50] opened 2015-05-18 08:17 UTC
When compiling python 2.7.9 with this project the modules mentioned in the title can't be build.  CMake reports for all of them the following or a similar error message:

```
$HOME\python-prefix\src\python\Modules\timemodule.c(104) : warning C4273: '_PyTime_DoubleToTimet' : inconsistent dll linkage
        $HOME\python-prefix\src\python\Include\timefuncs.h(17) : see previous definition of '_PyTime_DoubleToTimet'
$HOME\python-prefix\src\python\Modules\timemodule.c(1062) : error C2491: '_PyTime_FloatTime' : definition of dllimport function not allowed
```

To reproduce use this [CMakeLists.txt] file. Invoke it with `cmake -n "NMake Makefiles" ..` in a separate build directory.

[CMakeLists.txt]: https://gist.githubusercontent.com/adrianbroher/e5dde411f32e4ef72375/raw/7e5f3d607e19abe27b0057cc2b8b751e9dd0a85f/CMakeLists.txt

**Comment by jcfr** [comment] 2015-05-18 11:57
Hi Adrian, 

Would you mind trying to checkout this topic and check if things works better: https://github.com/jcfr/python-cmake-buildsystem/tree/ci-support-v2.7.8

Thanks
Jc

Ps: I am travelling for the coming days and won't be able to review. @thewtex  should be able to help out :)

**Comment by adrianbroher** [comment] 2015-05-18 19:10
Thanks for pointing out your fork.  Unfortunately it does not fix the problem.

I tried the following combinations:

branch | python version | status
--------- | ---------- | --------
[davidansome/master] | 2.7.3 | compiles
[jcfr/ci-support-v2.7.8] | 2.7.8 | fails
[jcfr/ci-support-v2.7.8] | 2.7.9 | fails

The 'fails' show the same error as reported in the initial post.

[davidansome/master]: https://github.com/davidsansome/python-cmake-buildsystem
[jcfr/ci-support-v2.7.8]: https://github.com/jcfr/python-cmake-buildsystem/tree/ci-support-v2.7.8

**Comment by jcfr** [comment] 2015-05-18 19:15
Hi
Thanks for checking. I ll have a look in two weeks as soon i m back from
travelling.

In the mean time, you are welcome to contribute a pullvrequest.

Thanks
Jc

--

**Comment by adrianbroher** [comment] 2015-06-22 09:16
Hello,

finally I could investigate this issue further and could successfully build python.

According to the [VTK wiki] the default python release links all extensions into the python.dll.  This project instead tries to build the extension as pyd libraries(?).  So I tried to make the time extension a builtin module and removing the `timemodule.c` from various places used in commit adrianbroher/python-cmake-buildsystem@3ad6d93 .  Now I don't know if this is the right way to fix the problem.  Given the fact that upstream provides a monolithic python.dll shouldn't all modules be builtins on Windows by default?

[VTK wiki]: http://www.vtk.org/Wiki/BuildingPythonWithCMake#Building_Python_for_Linux_or_Windows

**Comment by adrianbroher** [comment] 2015-07-06 10:28
> Now I don't know if this is the right way to fix the problem. Given the fact that upstream provides a monolithic python.dll shouldn't all extension be builtins on Windows by default?

Any feedback on this and the mentioned commit?  Should I make this a PR?

**Comment by jcfr** [comment] 2015-07-09 05:31
@adrianbroher @jrobcary  :100:  Thanks to you both the issue is now fixed in master. See 0a088b28eb4

**Closed** 2015-07-09 05:31 UTC
